<div id="fb-root"></div>
<div class="fb-comments"
    {% if FB_COMMENT_URL %}
    data-href="{{ FB_COMMENT_URL }}"
    {% else %}
    data-href="{{ request.build_absolute_uri }}"
    {% endif %}
    data-numposts="20" data-colorscheme="light"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=1427369857506585";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>