<div id="fb-root"></div>
<script>
(function($){
    {% if FB_COMMENT_URL %}
        var data_href="{{ FB_COMMENT_URL }}";
    {% else %}
        var data_href="{{ request.build_absolute_uri }}";
    {% endif %}
    var fbRoot = $("#fb-root");
    var width = fbRoot.parent().width();
    fbRoot.after("<div class=\"fb-comments\" data=numposts=\"20\" data-colorscheme=\"light\" data-href=\""
                    + data_href + "\" data-width=\"" + width + "\"></div>");
})(jQuery);
</script>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=1427369857506585";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>