{% load i18n %}
<div class="panel panel-default">
	<div class="panel-heading">
		{% trans "Accounts" %}
	</div>
	<div class="panel-body">
		<ul class="nav nav-pills nav-stacked">
			<li{% if active_profile %} class="active"{% endif %}>
				<a href="{% url 'accounts_profile' %}">{% trans 'Profile' %}</a>
			</li>
			{% if request.user.password != '!' %}
				<li{% if active_changepassword %} class="active"{% endif %}>
					<a href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
				</li>
			{% else %}
				<li{% if active_setpassword %} class="active"{% endif %}>
					<a href="{% url 'set_user_password' %}">{% trans 'Set password' %}</a>
				</li>
			{% endif %}
			<li{% if active_socialaccounts %} class="active"{% endif %}>
				<a href="{% url 'accounts_social_list' %}">{% trans 'Social accounts' %}</a>
			</li>
		</ul>
	</div>
</div>
{% include 'postman/_accounts_menu.phtml' %}
<div class="panel panel-default">
	<div class="panel-heading">
		{% trans "Books" %}
	</div>
	<div class="panel-body">
		<ul class="nav nav-pills nav-stacked">
			<li{% if active_favoritebook %} class="active"{% endif %}>
				<a href="{% url 'favorite_books' %}">{% trans 'Favorite books' %}</a>
			</li>
		</ul>
	</div>
</div>