{% extends "base.html" %}
{% load i18n %}
{% load static_tags %}
{% load back_url_tag %}
{% block title %}{% trans 'Log in' %}{% endblock %}
{% load_css static /accounts/zocial.css %}
{% block content %}
{% if not onetime_show_notification.CAN_LOGIN_WITH_OLD_TANGTHUVIEN_ACCOUNT %}
<div class="row">
    <div class="col-lg-12">
        <div class="bs-example">
            <div class="alert alert-dismissable alert-info">
                <button type="button" class="close onetime-notification" data-dismiss="alert" data-key="CAN_LOGIN_WITH_OLD_TANGTHUVIEN_ACCOUNT">×</button>
                <p>
                    {% trans "You can login with tangthuvien forum account on this site" %}.
                </p>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="login_page">
	<div class="row">
		<div class="col-lg-6">
			<div class="well">
				{% if not user.is_authenticated %}
					<form method="post" action="{% url 'django.contrib.auth.views.login' %}" id="login_form" class="form-horizontal">
						{% csrf_token %}
						<fieldset>
							<legend>{% trans 'Log in with your website account' %}</legend>
							{% include "general/form_render.phtml" %}
			            	<div class="form-group">
		                    	<div class="col-lg-9 col-lg-offset-3">
		                      		<button type="submit" id="id_login" class="btn btn-primary">{% trans 'Log in' %}</button> 
		                    	</div>
		                  	</div>
						</fieldset>
						<input type="hidden" name="next" value="{{ next }}" />
					</form>
				{% else %}
					<p>{% trans 'You are currently logged in as' %} {{request.user.first_name}} {{request.user.last_name}}</p>
				{% endif %}
			</div>
		</div>
		<div class="col-lg-6">
			<div class="well">
				{% if not user.is_authenticated %}
				<p>{% trans 'Or log in with your social network account:' %}</p>
				{% else %}
				<p>{% trans 'Associate your account with social network account:' %}</p>
				{% endif %}
				<div id="social_login">
				    <a href="{% url 'socialauth_begin' 'facebook' %}{% back_url %}" class="zocial facebook" 
				    	id="facebook" title="{% trans 'Login with your Facebook account' %}">
				    	{% trans 'Facebook' %}
				    </a>
				    <a href="{% url 'socialauth_begin' 'twitter' %}{% back_url %}"  class="zocial twitter"
				    	id="twitter" title="{% trans 'Login with your Twitter account' %}">
				    	{% trans 'Twitter' %}
				    </a>
				    <a href="{% url 'socialauth_begin' 'google-oauth2' %}{% back_url %}"  class="zocial googleplus"
				    	id="google" title="{% trans 'Login with your Google account' %}">
				    	{% trans 'Google' %}
				    </a>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}