{% extends "master.phtml" %}
{% load i18n %}
{% load back_url_tag %}
{% block title %}{% trans 'Log in' %}{% endblock %}
{% block content %}
<div class="login_page">
	<div class="row">
		<div class="col-lg-6">
			<div class="well">
				{% if not user.is_authenticated %}
					<form method="post" action="{% url 'django.contrib.auth.views.login' %}" id="login_form" class="form-horizontal">
						{% csrf_token %}
						<fieldset>
							<legend>{% trans 'Log in with your website account' %}</legend>
							{% if form.errors %}
								<div class="alert alert-danger">
									{{form.errors}}
					            </div>
				            {% endif %}
							<div class="form-group">
			                    <label for="{{ form.username.auto_id }}" class="col-lg-3 control-label">{{ form.username.label }}</label>
			                    <div class="col-lg-9">
			                    	{{ form.username }}
			                    </div>
			            	</div>
							<div class="form-group">
			                    <label for="{{ form.password.auto_id }}" class="col-lg-3 control-label">{{ form.password.label }}</label>
			                    <div class="col-lg-9">
			                    	{{ form.password }}
			                    </div>
			            	</div>
			            	<div class="form-group">
		                    	<div class="col-lg-9 col-lg-offset-3">
		                      		<button type="submit" id="id_login" class="btn btn-primary">{% trans 'Log in' %}</button> 
		                    	</div>
		                  	</div>
						</fieldset>
						<input type="hidden" name="next" value="{{ next }}" />
					</form>
				{% else %}
					<p>{% trans 'You are currently logged in as' %} {{request.user.first_name}} {{request.user.last_name}}</p>
				{% endif %}
			</div>
		</div>
		<div class="col-lg-6">
			<div class="well">
				{% if not user.is_authenticated %}
				<p>{% trans 'Or log in with your social network account:' %}</p>
				{% else %}
				<p>{% trans 'Associate your account with social network account:' %}</p>
				{% endif %}
				<div id="social_login">
				    <a href="{% url 'socialauth_begin' 'facebook' %}{% back_url %}" id="facebook" title="{% trans 'Login with your Facebook account' %}">{% trans 'Login with Facebook' %}</a>
				    <a href="{% url 'socialauth_begin' 'twitter' %}{% back_url %}" id="twitter" title="{% trans 'Login with your Twitter account' %}">{% trans 'Login with Twitter' %}</a>
				    <a href="{% url 'socialauth_begin' 'google-oauth2' %}{% back_url %}" id="google" title="{% trans 'Login with your Google account' %}">{% trans 'Login with Google' %}</a>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}