{% extends "master.phtml" %}
{% load i18n static %}

{% block title %}{% trans 'Password change' %}{% endblock %}

{% block content %}<div id="content-main">

<form action="" method="post" id="set_password_form">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% blocktrans count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
{% endif %}

<h1>{% trans 'Password set' %}</h1>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">{% trans 'New password' %}:</label>{{ form.new_password1 }}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">{% trans 'Password (again)' %}:</label>{{ form.new_password2 }}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Set password' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

{% endblock %}
