{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Change password' %}{% endblock %}
{% block content %}
<div class="login_page">
	<div class="row">
		<div class="col-lg-9">
			<div class="well">
				<form method="post" id="change_password_form" class="form-horizontal" action="{% url 'django.contrib.auth.views.password_change' %}">
					{% csrf_token %}
					<fieldset>
						<legend>{% trans 'Change password' %}</legend>
			        	{% include "general/form_render.phtml" %}
		            	<div class="form-group">
	                    	<div class="col-lg-9 col-lg-offset-3">
	                      		<button type="submit" id="id_login" class="btn btn-primary">{% trans 'Change password' %}</button> 
	                    	</div>
	                  	</div>
					</fieldset>
				</form>
			</div>
		</div>
		<div class="col-lg-3">
			{% include 'accounts/_user_menu.phtml' with active_changepassword=1 %}
		</div>
	</div>
</div>


{% endblock %}