{% extends "master.phtml" %}
{% load i18n static %}

{% block title %}{% trans 'Social accounts' %}{% endblock %}

{% block content %}<div id="content-main">

<form action="" method="post" id="set_password_form">{% csrf_token %}
    <div>
        <h1>{% trans 'Social accounts' %}</h1>
        <ul id="social_accounts" class="list">
            {% for social in socials %}
            <li class="item social social-{{social.provider}}">
                {{social.provider}} - {{social.uid}}
            </li>
            {% endfor%}
        </ul>
    </div>
</form></div>

{% endblock %}
