{% extends "accounts/base.phtml" %}

{% load i18n %}
{% load static_tags %}

{% load_js static /thankshop/myitem.js %}
{% load_js static /angular/ApiHandler.js %}
{% load_js static /thankshop/angular.js %}

{% block content %}
<div ng-controller="InventoryController">
    <div class="row" id="my_items">
        <div class="col-lg-4 item" item-id="{% verbatim %}{{item.id}}{% endverbatim %}" ng-repeat="item in items">
            <span>{% verbatim %}{{item.name}}{% endverbatim %}</span>
            <button class="btn btn-default view" ng-click="showDetail(item)">{% trans "Detail" %}</button>
        </div>
    </div>
    <!-- Modal -->
    <div id="item_information" class="modal fade" data-width="600" data-height="310"
        tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <form id="new-author-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <h4 class="modal-title title">{% verbatim %}{{item.name}}{% endverbatim %}</h4>
                    </div>
                    <div class="modal-body">
                        <img class="image" ng-src="{% verbatim %}{{item.image_url}}{% endverbatim %}" />
                        <div class="description">{% verbatim %}{{item.long_description}}{% endverbatim %}</div>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </form>
    </div><!-- /.modal -->
</div>
{% endblock content %}
