{% extends "accounts/base.phtml" %}

{% load i18n %}

{% block footer-js %}
    {{ block.super }}
    <script src="{{STATIC_URL}}js/angular/angular.js"></script>
    <script src="{{STATIC_URL}}js/angular/ApiHandler.js"></script>
    <script src="{{STATIC_URL}}js/thankshop/inventory.js"></script>
{% endblock %}

{% block accounts-content %}
<div ng-controller="InventoryController">
    <div class="row" id="my_items">
        <div class="col-lg-4 item" item-id="{% verbatim %}{{item.id}}{% endverbatim %}" ng-repeat="item in items" ng-click="showDetail(item)">
            <div class="well" >
                <div class="image text-center"><img ng-src="{{MEDIA_URL}}{% verbatim %}{{item.image_url}}{% endverbatim %}" /></div>
                <div>{% verbatim %}{{item.name}}{% endverbatim %}</div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div id="item_information" class="modal fade" data-width="600" data-height="310"
        tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <form id="new-author-form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <h4 class="modal-title title">{% verbatim %}{{item.name}}{% endverbatim %}</h4>
                    </div>
                    <div class="modal-body">
                        <img class="image" ng-src="{% verbatim %}{{item.image_url}}{% endverbatim %}" />
                        <div class="description">{% verbatim %}{{item.long_description}}{% endverbatim %}</div>
                    </div>
                    <div class="modal-footer" ng-show="item.has_action">
                        <button type="submit" ng-click="activate(item)">{% trans "Activate"%}</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </form>
    </div><!-- /.modal -->
</div>
{% endblock accounts-content %}
