{% extends 'base.html' %}
{% load i18n %}
{% load static_tags %}

{% load_js static /thankshop/homepage.js %}

{% block content %}
<div id="thankshop">
	<div class="row" id="items">
		{% for item in items %}
		<div class="col-lg-3 item">
			<div class="name">{{item.name}}</div>
			<div class="short_description">{{item.short_description}}</div>
			<div class="long_description">{{item.long_description}}</div>
			<div class="price">{{item.price}}</div>
			<button class="btn btn-default buy" data-item_id="{{item.id}}">{% trans "Buy" %}</button>
		</div>
		{% endfor %}
	</div>
</div>
<!-- Modal -->
<div id="buy-confirmation" class="modal fade" data-width="600"
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">{% trans 'You are going to buy this item' %}</h4>
            </div>
            <div class="modal-body">
            	<form action="{% url 'thankshop_buy_item_ajax' %}" method="POST">
					{% csrf_token %}
					<input type="hidden" name="item_id" value="0" />
            	</form>
				<div class="name"></div>
				<div class="short_description"></div>
				<div class="long_description"></div>
				<div class="price"></div>
            </div>
            <div class="modal-footer">
            	<button class="btn btn-primary accept">{% trans "Buy" %}</button>
            	<button class="btn btn-default cancel" data-dismiss="modal">{% trans "Cancel" %}</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}
