{% load i18n %}
{% load url from future %}
<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a href="{% url 'homepage' %}" class="navbar-brand">{{SITE_NAME}}</a>
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse" id="navbar-main">
			<ul class="nav navbar-nav">
				<li>
					<a href="{% url 'books_home' %}">{% trans "Truyện" %}</a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						{% trans 'Đổi style' %}
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						{% for style in AVAILABLE_STYLES %}
							<li{% if style == CURRENT_STYLE %} class="active"{% endif %}><a href="{% url 'change_style' style %}">{{style|capfirst}}</a></li>
						{% endfor %}
					</ul>
				</li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						{{user.username}}
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'accounts_profile' %}">{% trans 'Trang cá nhân' %}</a></li>
						<li><a href="{% url 'logout' %}">{% trans 'Đăng xuất' %}</a></li>
					</ul>
				</li>
				{% else %}
				<li>
					<a href="{% url 'login' %}?next={{request.path}}">{% trans "Đăng nhập" %}</a>
				</li>
				{% endif %}
			</ul>

		</div>
	</div>
</div>