{% load i18n %}
{% load url from future %}
<div class="page-header" id="banner">
	<div class="row">
		<div class="col-lg-6">
			<h1><a href="{% url 'homepage' %}" title="{% trans "Tàng Thư Viện" %}" rel="home">{{SITE_NAME}}</a></h1>
			<p class="lead">
				{% trans "Truyện kiếm hiệp." %}
			</p>
		</div>
		<div class="col-lg-6">
			<div class="bsa well">
				<div id="bsap_1277971" class="bsap_1277971 bsap"></div>
			</div>
		</div>
	</div>
</div>