{% load bootstrap %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        {{error}}
    </div>
    {% endfor %}
    {% for field in form %}
        {% if field.is_hidden %}
            {{field}}
        {% else %}
        	<div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.auto_id }}" class="col-lg-3 control-label">{{ field.label }}</label>
                <div class="col-lg-9">
                	{{ field|add_bootstrap_field }}
                	{% if field.errors %}
                    	<div class="alert alert-danger">
                    		{{field.errors}}
                    	</div>
                	{% endif %}
                </div>
        	</div>
        {% endif %}
    {% endfor %}
{{ form.media }}