{% for field in form %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.auto_id }}" class="col-lg-3 control-label">{{ field.label }}</label>
        <div class="col-lg-9">
        	{{ field }}
        	{% if field.errors %}
            	<div class="alert alert-danger">
            		{% if field.errors %}{{field.errors}}{% endif %}
            	</div>
        	{% endif %}
        </div>
	</div>
{% endfor %}