{% load i18n %}
{% load file_filters %}
<div class="col-lg-12">
    <div id="attachments" class="well well-sm">
    	<h3>{% trans 'Book attachments' %}</h3>
    	{% include 'book/_upload_attachment.phtml' %}
    	<ul class="nav nav-pills nav-stacked">
    		{% for attachment in book.attachment_set.all %}
    			{% if attachment.is_approved  or perms.book.can_approve_attachment or attachment.uploader.id = request.user.id %}
    				<li id="book_attachment_{{attachment.id}}">
    					{% if request.user.book_profile.can_download_attachment %}
    					<a href="{{attachment.download_url}}">
    					{% else %}
    					<span title="{% trans 'You need to login to be able to download' %}">
    					{% endif %}
    						<span class="filename">{{attachment.name}}</span>
    						<span class="filesize">({{attachment.size|size_in_kb}})</span>
    						<span class="date pull-right">{{attachment.creation_date|date:"D d M Y"}}</span>
    					{% if request.user.book_profile.can_download_attachment %}
    					</a>
    					{% else %}
    					</span>
    					{% endif %}
						{% if not attachment.is_approved and request.user.book_profile.can_approve_attachment %}
							<button class="btn btn-success approve" data-attachment_id="{{attachment.id}}">{% trans "Approve" %}</button>
						{% endif %}
    				</li>
    			{% endif %}
    		{% endfor %}
    	</ul>
    </div>
    {% if request.user.book_profile.can_approve_attachment %}
    <script>
    jQuery(function($){
    	var ajaxConf = {};
    	ajaxConf['url'] = "{% url 'approve_book_attachment_ajax' %}";
    	ajaxConf['data'] = {};
    	$("#attachments .approve").click(function(){
    		var _this = this;
    		ajaxConf['success'] = function(data){
    			if(data['status'] == 'success'){
    				$(_this).remove();
    			} else {
    				alert(data['message']);
    			}
    		}
    		ajaxConf['data']['attachment_id'] = $(this).data('attachment_id');
    		$.ajax(ajaxConf);
    		return false;
    	});
    });
    </script>
    {% endif %}
</div>