{% load i18n %}
{% load static_tags %}
{% if perms.book.can_generate_prc %}
	{% load_js url http://localhost:1234/socket.io/socket.io.js %}
	<div class="well" id="generate_book_prc_div">
		<a href="{% url 'generate_book_prc' book.id %}" class="btn btn-default disabled"
			id="generate_book_prc">
			{% trans "Generate PRC" %}
		</a>
		<div class="progress progress-striped active" style="display: none">
			<div class="progress-bar" style="width: 100%"></div>
		</div>
		<script>
			jQuery(window).load(function(){
				var socket = io.connect('http://localhost:1234');
				(function($){

					socket.on('generate_book_prc_{{book.id}}', function(data){
						console.log(data);
						$("#generate_book_prc_div .progress .progress-bar").addClass('progress-bar-success');
						$("#generate_book_prc_div .progress .progress-bar").html("{% trans 'PRC was generated' %}");
						append_new_book_attachment(data.attachment);
						setTimeout(function(){
							$("#generate_book_prc_div .progress").fadeOut();
						}, 1000);
					});

					$("#generate_book_prc").click(function(){
						$("#generate_book_prc_div .progress .progress-bar").html("{% trans 'PRC is generating' %}");
						$("#generate_book_prc_div .progress .progress-bar").removeClass('progress-bar-success');
						$("#generate_book_prc_div .progress").show();
						socket.emit('generate_book_prc', { book_id: '{{book.id}}' });
						return false;
					});
					$("#generate_book_prc").removeClass('disabled');
				})(jQuery);

			});
		</script>
	</div>
{% endif %}
