{% load i18n %}
{% load static_tags %}
{% load_css static /book/style.css %}
{% if showcheckbox and not onetime_show_notification.SELECT_BOOK_IN_LIST %}
<div class="row">
	<div class="col-lg-12">
		<div class="bs-example">
			<div class="alert alert-dismissable alert-info">
				<button type="button" class="close onetime-notification" data-dismiss="alert" data-key="SELECT_BOOK_IN_LIST">×</button>
				<p>
					{% trans "Bạn có thể chọn truyện bằng cách click vào phần trống trong tiêu đề truyện" %}.
					<img src="{{ STATIC_URL }}img/book/help/book_select_before_click.png" />
					<img src="{{ STATIC_URL }}img/book/help/book_select_after_click.png" />
				</p>
			</div>
		</div>
	</div>
</div>
{% endif %}
<div id="books" class="list {{class}}">
	{% for book in books %}
		{% if forloop.counter0|divisibleby:"4" %}<div class="row">{% endif %}
			<div class="col-lg-3 item book" item_id="{{ book.id }}"{% if not book.is_read and not book.is_read_by_current_user %}unread="yes"{% endif %}>
				<div class="panel panel-default">
					<div class="panel-heading">
						{% if showcheckbox %}
						<input type="checkbox" name="ids[]" value="{{book.id}}">
				        {% endif %}
						<h4>
							<a href="{{ book.full_url }}">{{book.title}}</a>
						</h4>
					</div>
					<div class="panel-body">
	                	<a class="title" href="{{ book.full_url }}"><img src="{{ MEDIA_URL }}{{book.cover_thumb}}" /></a>
	                	<h5><a href="books/author/{{book.author.slug}}">{{book.author.name}}</a></h5>
	          		</div>
				</div>
			</div>
		{% if forloop.last or forloop.counter|divisibleby:"4" %}</div>{% endif %}
	{% endfor %}
</div>
{% if showcheckbox %}
<script>
jQuery(function($) {
	$("#books .panel").click(function() {
		var state = ! $("input[type='checkbox']").prop('checked')
		$("input[type='checkbox']").prop('checked', state);
		$(this).toggleClass('panel-default');
		$(this).toggleClass('panel-success');
	});
});
</script>
{% endif %}