{% load i18n %}
{% load static_tags %}
{% if perms.book.can_generate_prc %}
    {% load_js url http://localhost:1234/socket.io/socket.io.js %}
    {% load_js static /book/generate_prc.js %}
    <div class="col-lg-3">

    <div class="well" id="generate_book_prc_div">
        <a href="{% url 'generate_book_prc' book.id %}" class="btn btn-default disabled"
            id="generate_book_prc">
            {% trans "Generate PRC" %}
        </a>
        <div class="progress progress-striped active" style="display: none">
            <div class="progress-bar" style="width: 100%"></div>
        </div>
        <script>
            jQuery(window).load(function(){
                generate_prc_socket_io({{book.id}});
            });
        </script>
    </div>
    </div>
{% endif %}
