{% load i18n %}
<div class="panel panel-default rating" id="book_rating">
	<div class="panel-heading">{% trans 'Rate book' %}</div>
	<div class="panel-body">
		<div class="result">
			{% blocktrans with book.rating.average_result as averate and book.rating.rating_count as rating_count %}
				Was rated <strong><span class="average-result">{{averate}}</span></strong>
				over <strong><span class="rating-count">{{rating_count}}</span></strong> ratings
			{% endblocktrans %}
		</div>
		<div class="rate-star">
			{% for i in book.rating.rating_range %}
			<button class="btn btn-default rate-star-{{i}}" data-rate-number="{{i}}"
			{% if book.rated_by_current_user %}
				disabled='disabled'
			{% elif not user.is_authenticated %}
			disabled='disabled' class='login_required'
			{% endif %}>{{i}}</button>
			{% endfor %}
		</div>
	</div>
</div>
<script type="text/javascript">
(function($){
	$("#book_rating .rate-star button").click(function(){
		var clickedButton = this;
		rateNumber = $(this).data('rate-number');

		$("#book_rating .rate-star button").attr('disabled', true);
		resultSpan = $("#book_rating .average-result");
		countSpan = $("#book_rating .rating-count");

		ratingCount = parseInt(countSpan.html());

		var newResult = (ratingCount * parseFloat(resultSpan.html()) + rateNumber) / (ratingCount + 1);
		newResult = newResult.toFixed(2);

		resultSpan.html(newResult);
		countSpan.html(ratingCount + 1);

		request = {};
		request['url'] = '{% url "submit_book_rating" %}';
		request['type'] = 'POST';
		request['data'] = {};
		request['data']['number'] = rateNumber;
		request['data']['book_id'] = '{{book.id}}';
		request['success'] = function(data){
			resultSpan.html(data['average_result'].toFixed(2));
			countSpan.html(data['rating_count']);
			$(clicked_button).removeClass('loading');
		}
		$(clickedButton).addClass('loading');
		$.ajax(request);
	});
})(jQuery);
</script>