{% load i18n %}
{% load statig_tags %}

{% load_js static /book/rating.js %}

<div class="panel panel-default rating" id="book_rating">
	<div class="panel-heading">{% trans 'Rate book' %}</div>
	<div class="panel-body">
		<div class="result">
			{% blocktrans with book.rating.average_result as averate and book.rating.rating_count as rating_count %}
				Was rated <strong><span class="average-result">{{averate}}</span></strong>
				over <strong><span class="rating-count">{{rating_count}}</span></strong> ratings
			{% endblocktrans %}
		</div>
		<div class="rate-star">
			{% for i in book.rating.rating_range %}
			<button class="btn btn-default rate-star-{{i}}" data-rate-number="{{i}}" data-book_id="{{book.id}}"
			{% if book.rated_by_current_user %}
				disabled='disabled'
			{% elif not user.is_authenticated %}
			disabled='disabled' class='login_required'
			{% endif %}>{{i}}</button>
			{% endfor %}
		</div>
	</div>
</div>