{% load i18n %}
{% load simple_filters %}
{% include 'general/bootstrap_modal_requirement.phtml' %}
<button type="button" data-toggle="modal" data-target="#config-modal"
    class="btn btn-default config">{% trans 'Config' %}</button>
<!-- Modal -->
<div id="config-modal" class="modal fade" data-width="600" data-height="{{config_reading_section_form.fields|length|multiple:70}}" 
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="config-reading-section-form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">{% trans 'Config reading section' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'general/form_render.phtml' with form=config_reading_section_form %}
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-default" data-dismiss="modal">
                        Cancel
                    </button>
                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
</div><!-- /.modal -->
<script>
(function($){
    $("#config-reading-section-form select").change(function(){
        $("#chapter .content").css($(this).data('css-name'), $(this).val());
    });
    $("#config-reading-section-form").submit(function(){
        var ajaxConf = {}
        ajaxConf['url'] = '{% url "ajax_book_reading_config" %}';
        ajaxConf['data'] = $(this).serialize();
        ajaxConf['type'] = 'POST';
        ajaxConf['complete'] = function(){
            $("#config-modal").modal("hide");
            $("#config-reading-section-form button[type=submit] .loading").remove();
        }
        $("#config-reading-section-form button[type=submit]").append(LOADING_IMAGE_HTML);
        $.ajax(ajaxConf);
        return false;
    });
    $("#config-reading-section-form button[type=reset]").click(function(){
        $("#config-reading-section-form")[0].reset();
        $("#config-reading-section-form select").change();
    });
    
})(jQuery);
</script>