{% load i18n %}
{% load static_tags %}

{% load_css static /bootstrap-modal/bootstrap-modal-bs3patch.css %}
{% load_css static /bootstrap-modal/bootstrap-modal.css %}

{% load_js static /bootstrap-modal/bootstrap-modalmanager.js %}
{% load_js static /bootstrap-modal/bootstrap-modal.js %}
<!-- Modal -->
<div id="new-author-form-div" class="modal fade" data-width="600" data-height="310"
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="new-author-form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">{% trans 'Add author' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'general/form_render.phtml' with form=form.author_form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn btn-primary">
                        Add
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
</div><!-- /.modal -->
<!-- Modal -->
<div id="new-type-form-div" class="modal fade" data-width="600" 
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="new-type-form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">{% trans 'Add type' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'general/form_render.phtml' with form=form.type_form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn btn-primary">
                        Add
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
</div><!-- /.modal -->
<script>
    jQuery(window).load(function(){
        jQuery.fn.modalmanager.defaults.resize = true;
        
        (function($){
            var new_author_option = document.createElement('option');
            $(new_author_option)
                .html(STR_CREATE_NEW)
                .prop('value', '-1');
            $("#{{form_id}} select[name='author']").change(function(){
                if($(this).val() == '-1'){
                    $('#new-author-form-div').modal('show'); //it seem that the modal was destroyed and re-created
                    $('#new-author-form-div').on('hide.bs.modal', function(){
                        $("#{{form_id}} select[name='author']").val('');
                        $("#{{form_id}} select[name='author']").change();
                    });
                }
            });
            $("#{{form_id}} select[name='author'] option:first").after(new_author_option);
            $("#new-author-form").submit(function(){
                var _this = this;
                var ajaxConf = {}
                ajaxConf['url'] = '{% url "add_book_author_ajax" %}';
                ajaxConf['data'] = $(this).serialize();
                ajaxConf['type'] = 'POST';
                ajaxConf['success'] = function(data){
                    if(data['success']){
                        var added = false;
                        var new_option = document.createElement('option');
                        $(new_option)
                            .prop('value', data['id'])
                            .html(data['name']);
                        
                        $("#{{form_id}} select[name='author'] option").slice(2).each(function(){
                            if(added){
                                return;
                            }
                            if($(this).html() > data['name']){
                                added = true;
                                $(this).before(new_option);
                            }
                        });
                        if(!added){
                            $("#{{form_id}} select[name='author']").append(new_option);
                        }
                        
                        // hide modal first
                        $('#new-author-form-div').modal('hide');
                        $("#{{form_id}} select[name='author']").val(data['id']);
                    }
                };
                ajaxConf['complete'] = function(){
                    $("[type='submit'] img.loading", _this).remove();
                };
                $("[type='submit']", _this).append(LOADING_IMAGE_HTML);
                $.ajax(ajaxConf);
                return false;
            });
            
            var new_type_option = document.createElement('option');
            $(new_type_option)
                .html(STR_CREATE_NEW)
                .prop('value', '-1');
            $("#{{form_id}} select[name='ttv_type']").change(function(){
                if($(this).val() == '-1'){
                    $('#new-type-form-div').modal('show');
                    $('#new-type-form-div').on('hide.bs.modal', function(){
                        $("#{{form_id}} select[name='ttv_type']").val('');
                        $("#{{form_id}} select[name='ttv_type']").change();
                    });
                }
            });
            $("#{{form_id}} select[name='ttv_type'] option:first").after(new_type_option);
            $("#new-type-form").submit(function(){
                var _this = this;
                var ajaxConf = {}
                ajaxConf['url'] = '{% url "add_book_type_ajax" %}';
                ajaxConf['data'] = $(this).serialize();
                ajaxConf['type'] = 'POST';
                ajaxConf['success'] = function(data){
                    if(data['success']){
                        var added = false;
                        var new_option = document.createElement('option');
                        $(new_option)
                            .prop('value', data['id'])
                            .html(data['name']);
                        
                        $("#{{form_id}} select[name='ttv_type'] option").slice(2).each(function(){
                            if(added){
                                return;
                            }
                            if($(this).html() > data['name']){
                                added = true;
                                $(this).before(new_option);
                            }
                        });
                        if(!added){
                            $("#{{form_id}} select[name='ttv_type']").append(new_option);
                        }
                        
                        // hide modal first
                        $('#new-type-form-div').modal('hide');
                        $("#{{form_id}} select[name='ttv_type']").val(data['id']);
                    }
                };
                ajaxConf['complete'] = function(){
                    $("[type='submit'] img.loading", _this).remove();
                };
                $("[type='submit']", _this).append(LOADING_IMAGE_HTML);
                $.ajax(ajaxConf);
                return false;
            });
        })(jQuery);
    });
</script>