{% load i18n %}
{% load static_tags %}

{% load_js static /book/inline_add_author_and_book_type.js %}

{% include 'general/bootstrap_modal_requirement.phtml' %}
<!-- Modal -->
<div id="new-author-form-div" class="modal fade" data-width="600" data-height="310"
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="new-author-form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">{% trans 'Add author' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'general/form_render.phtml' with form=author_form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn btn-primary">
                        Add
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
</div><!-- /.modal -->
<!-- Modal -->
<div id="new-type-form-div" class="modal fade" data-width="600" 
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="new-type-form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">{% trans 'Add type' %}</h4>
                </div>
                <div class="modal-body">
                    {% include 'general/form_render.phtml' with form=type_form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn btn-primary">
                        Add
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </form>
</div><!-- /.modal -->
<script>
    jQuery(window).load(function(){
    	inline_add_author_and_type("{{form_id}}");
    });
</script>