{% load i18n %}
{% load static_tags %}
{% if request.user.book_profile.can_upload_attachment %}
	{% load_css static /plugins/jquery.fileupload.css %}

	{% load_js static /plugins/jquery.fileupload.js %}
	{% load_js static /plugins/jquery.iframe-transport.js %}
	{% load_js static /plugins/vendor/jquery.ui.widget.js %}
	<form id="upload_attachment">
		{% csrf_token %}
		<span class="btn btn-success fileinput-button">
	        <i class="glyphicon glyphicon-plus"></i>
	        <span>Select files...</span>
	        <!-- The file input field used as target for the file upload widget -->
	        <input id="fileupload" type="file" name="file" class="upload" multiple>
	    </span>
		<div class="progress progress-striped active" id="process_bar">
	        <div class="progress-bar progress-bar-info" style="width: 0%"></div>
	    </div>
	</form>
	<script>
	(function($){
		function get_size_in_kb(bytes){
			var kb = parseInt(bytes / 1024);
			return kb + " KB";
		}

		append_new_book_attachment = function (file){
			var file_id = 'book_attachment_' + file['id'];
			$('#' + file_id).remove();
            $("#attachments ul").prepend(
            	$("<li></li>").prop('id', file_id).html(
            		$("<a></a>")
            			.attr('href', file['url'])
            			.append(
            				$("<span></span>").addClass("filename").html(file['name'])
            			)
            			.append(" ")
            			.append(
            				$("<span></span>").addClass("filesize").html(get_size_in_kb(file['size']))
            			)
            			.append("<br />")
            			.append(
            				$("<span></span>").addClass("date").html(file['creation_date'])
            			)
            	)
            );
		}
		$(window).load(function(){
		    $('#fileupload').fileupload({
		        url: "{% url 'upload_book_attachment_ajax' book.id %}",
		        dataType: 'json',
		        beforeSend: function(){
		        	$('#upload_attachment .progress').show();
		        },
		        done: function (e, data) {
		            $.each(data.result.files, function (index, file) {
		            	append_new_book_attachment(file);
		            });
		            $('#upload_attachment .progress').hide();
		        },
		        progressall: function (e, data) {
		            var progress = parseInt(data.loaded / data.total * 100, 10);
		            $('#upload_attachment .progress .progress-bar').css(
		                'width',
		                progress + '%'
		            );
		        }
		    }).prop('disabled', !$.support.fileInput)
		        .parent().addClass($.support.fileInput ? undefined : 'disabled');
			$('#upload_attachment .progress').hide();
		});
	})(jQuery);
	</script>
{% else %}
	{% if request.user.is_authenticated %}
		<span class="upload">{% trans 'You reach upload count limited' %}</span>
	{% else %}
		<span class="upload">{% trans 'You need to log-in to upload document' %}</span>
	{% endif %}
{% endif %}
