{% extends 'book/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Edit chapter'%}{% endblock %}

{% block content %}
<div id="post_new_chapter">
	<div class="row">
		<div class="col-lg-9">
			<div class="well">
				<form method="post" action="{% url 'edit_chapter' chapter.id %}" class="form-horizontal" id="new-chapter-form">
					{% csrf_token %}
					<fieldset>
						<legend>{% trans 'Edit chapter' %}</legend>
						{% include 'general/form_render.phtml' %}
						<div class="form-group">
		                    <div class="col-lg-9 col-lg-offset-3">
	                      		<button type="submit" id="id_submit" class="btn btn-primary">{% trans 'Save' %}</button>
	                    	</div>
	                  	</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
