{% extends 'base.html' %}
{% load i18n %}
{% load static_tags %}
{% load book_language %}

{% block title %}{{book.title}}{% endblock %}

{% block meta-description %}{{book.description|striptags|escapejs}}{% endblock %}

{% load_css static /book/style.css %}

{% block content %}
{% include 'book/onetime_notification/user_log_notification.phtml' %}
<div class="row">
    <h3 class="col-lg-9">{{book.title}} / {{book.author.name}}</h3>
</div>
<div class="row" id="book" item_id="{{book.id}}">
    <div class="row">
        <div class="col-lg-4">
            {% if book.cover %}
                <img src="{{book.cover.url}}" />
            {% else %}
                <img src="{{STATIC_URL}}img/book/cover.jpg" />
            {% endif %}
        </div>
        <div class="col-lg-8">
            <div class="row">
                <div class="col-lg-4">{% trans "Author" %}</div>
                <div class="col-lg-8">{{book.author.name}}</div>
            </div>
            <div class="row">
                <div class="col-lg-4">{% trans "Alternate titles" %}</div>
                <div class="col-lg-8">{{book.chapters_count}}</div>
            </div>
            <div class="row">
            	<div class="col-lg-4">{% trans "Languages" %}</div>
            	<div class="col-lg-8" id="languages">
            		{% get_preference_language_id as language_id %}
            		{% for language in book.languages.all %}
            			<button type="button" data-id="{{language.id}}"
            				class="btn {% if language.id == language_id %}btn-success{% else %}btn-default{% endif %} btn-xs language language-{{language.slug}}">
            				{{language.name}}
            			</button>
            		{% endfor %}
            	</div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <!-- AddThis Button BEGIN -->
                    <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
                    <a class="addthis_button_preferred_1"></a>
                    <a class="addthis_button_preferred_2"></a>
                    <a class="addthis_button_preferred_3"></a>
                    <a class="addthis_button_preferred_4"></a>
                    <a class="addthis_button_compact"></a>
                    <a class="addthis_counter addthis_bubble_style"></a>
                    </div>
                    <script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>
                    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-527328af0f405b47"></script>
                    <!-- AddThis Button END -->
                </div>
            </div>
        </div>
    </div>
    <div clas="row">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans "Introduction" %}</div>
            <div class="panel-body">{{book.description|safe}}</div>
        </div>
    </div>
    <div class="row">
        <div id="chapters_list" class="col-lg-6">
            <h3>{% trans "Posted chapters" %}</h3>
            <table class="table table-striped table-bordered table-hover">
                <tbody>
                    {% if book.chapters_list|length > 10 %}
                        {% for page_info in book.chapters_list|slice:":4" %}
                        <tr>
                            <td><a href="{% url 'read_book_chapter' book.slug page_info.0 %}">{{ page_info.0 }} - {{ page_info.1 }}</a></td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td>... ... ...</td>
                        </tr>
                        {% for page_info in book.chapters_list|slice:"-4:" %}
                            <tr>
                                <td><a href="{% url 'read_book_chapter' book.slug page_info.0 %}">{{ page_info.0 }} - {{ page_info.1 }}</a></td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        {% for page_info in book.chapters_list %}
                        <tr>
                            <td><a href="{% url 'read_book_chapter' book.slug page_info.0 %}">{{ page_info.0 }} - {{ page_info.1 }}</a></td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div id="testimonials" class="col-lg-6">
            <h3>{% trans "Testimonials" %}</h3>
            <script>
                var disqus_url = get_real_link("{% url 'book_read' book.slug %}") + "/reviews";
            </script>
            {% include 'disqus.phtml'%}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="panel panel-default start-reading">
                <div class="panel-body">
                    {% if request.user.is_authenticated and book_read_log %}
                        <a class="btn btn-primary" id="read_book"
                            href="{% url 'read_book_chapter' book.slug book_read_log.page %}">
                            {% trans "Continue reading" %}
                        </a>
                    {% else %}
                        <a class="btn btn-primary" id="read_book"
                            href="{% url 'read_book_chapter' book.slug book.chapters_list.0.0 %}">
                            {% trans "Start reading" %}
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% include 'book/_book_sync_copy.phtml' %}
        {% include 'book/_book_favorite.phtml' %}
        {% include 'book/_book_rating.phtml' %}
    </div>
    <div class="row">
        {% include 'book/_book_attachments.phtml' %}
    </div>
</div>
{% endblock %}
