{% extends "accounts/base.phtml" %}

{% load i18n %}
{% load static_tags %}

{% load_js static /jquery-sortable.js %}
{% load_js static /thankshop/angular.js %}
{% load_js static /bootbox.js%}
{% load_css static /book/style.css %}

{% block accounts-content %}
<div ng-controller="LanguageSettingController">
    <div class="row">
        <ul id="bookLanguages" class="list-group sortable">
            <li class="list-group-item" ng-repeat="language in languages">
                <span class="badge" data-id="{% verbatim %}{{language.id}}{% endverbatim %}">
                    {% verbatim %}{{$index + 1}}{% endverbatim %}
                </span>
                {% verbatim %}{{language.name}}{% endverbatim %}
            </li>
        </ul>
    </div>
    <div class="row text-center">
        <button type="button" class="btn btn-primary" ng-click="saveLanguageSetting()">
            {% trans "Save language setting" %}
        </button>
    </div>
</div>
<script>
    jQuery(function(){
        var $ = jQuery;
        $("#bookLanguages").sortable({
            placeholder: '<li class="list-group-item">...</li>',
            onDrop: function ($item, container, _super) {
                $item.removeClass("dragged").removeAttr("style");
                $("body").removeClass("dragging");
                $("#bookLanguages li span").each(function(index, element){
                    $(this).html(index + 1);
                });
            }
        });
        $("#saveLanguageSetting").click(function(){
            var data = [];
            $("#bookLanguages li span").each(function(){
                data.push($(this).data("id"));
            });
            $.ajax({
                type: "POST",
                dataType: "JSON",
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(data),
                beforeSend: function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", jQuery.cookie('csrftoken'));
                    $("#saveLanguageSetting").append(LOADING_IMAGE_HTML);
                },
                success: function(){
                    $("#saveLanguageSetting .loading").remove();
                },
                error: function(){
                    $("#saveLanguageSetting .loading").remove();
                    bootbox.alert(LANG_SYSTEM_ERROR_MESSAGE)
                }
            });
        });

        var reqModule = reqModule || angular.module('tangthuvien', []);
        LanguageSettingController = function($scope){
            $scope.languages = [{id: 1, name: 'English'}, {id: 2, name: 'Vietnamese'}]
        }

    })
</script>
{% endblock accounts-content %}