{% extends 'base.html' %}
{% load i18n %}
{% load static_tags %}

{% block title %}{{chapter.book.title}} - {% trans 'Page'%} {{chapter.number}}{% endblock %}

{% block meta-description %}{{chapter.book.description|striptags|escapejs}}{% endblock %}

{% load_css static /book/style.css %}

{% block content %}
<div class="row">
	<div class="col-lg-9">
	    <div class="row">
    		<h3 class="col-lg-9">{{book.title}} / {{book.author.name}}</h3>
            <div class="col-lg-3" id="read_config">
                {% include 'book/_config_reading_section.phtml' %}
            </div>
        </div>
		<div class="panel panel-default">
        	<div class="panel-body">
				{% include 'book/_read_pagination.phtml'%}
				<div id="chapters">
					<div id="chapter" class="item chapter" item_id="{{chapter.id}}">
						<h2><span class="number">{{chapter.number}}</span> - {{chapter.title}}</h2>
						<div class="content" style="{{config_reading_section_form.styles}}">{{chapter.content|safe}}</div>
					</div>
				</div>
				{% include 'book/_read_pagination.phtml'%}
            </div>
        </div>
        <div id="after-chapter-content" class="btn-group btn-group-justified">
            <a id="post-new-chapter" href="{% url 'post_new_chapter' chapter.book.id %}" class="btn btn-default">{% trans 'Add Chapter' %}</a>
        	{% if chapter.user.id = request.user.id %}
        	<a id="edit-chapter" href="{% url 'edit_chapter' chapter.id %}" class="btn btn-default">{% trans 'Edit Chapter' %}</a>
        	{% endif %}
        </div>
		<script>
		    var disqus_url = get_real_link("{% url 'book_read' chapter.book.slug %}");
		</script>
		{% include 'disqus.phtml'%}
	</div>
	<div class="col-lg-3 sidebar-margin-top">
		<div id="chapter-thank" class="panel panel-default">
			<div class="panel-heading">{% blocktrans with name=chapter.user.username %}Thank {{name}}{% endblocktrans %}</div>
			<div class="panel-body">
				<div class="thank-count">
					<button
						class="
						btn thank-button
						{% if chapter.thanked_by_current_user %}btn-disable
						{% elif not user.is_authenticated %}btn-disable login_required
						{% else %}btn-default
						{% endif %}"
						title="{% if chapter.thanked_by_current_user %}{% trans 'You thanked already' %}{% elif not user.is_authenticated %}{% trans 'Required you be logged-in to thank' %}{% else %}{% trans 'Thank the poster' %}{% endif %}"
						>
						<span class="count">{{chapter.thank_count}}</span> {% trans "thank(s)" %}
					</button>
				</div>
				<script type="text/javascript">
(function($){
	var thankButton = $("#chapter-thank .thank-button");
	var thankCountDiv = $("#chapter-thank .count");
	var thankCount = parseInt(thankCountDiv.text());
	function thank(event){
		thankButton
			.unbind('click', thank)
			.removeClass('btn-default')
			.addClass('btn-disable');
		var request = {};
		request['url'] = '{% url "summit_thank_request" %}';
		request['data'] = {};
		request['data']['chapter_id'] = '{{chapter.id}}';
		request['type'] = 'POST';
		request['success'] = function(data){
			console.log(data);
			thankButton.removeClass('loading');
		};
		thankButton.addClass('loading');
		$.ajax(request);

		thankCountDiv.html(thankCount + 1);
	}
	if(!thankButton.hasClass('btn-disable')){
		thankButton.click(thank)
	}
})(jQuery);
				</script>
				{% csrf_token %}
			</div>
		</div>
		{% if book.copy.thread_id %}
		<div class="panel panel-default copy">
			<div class="panel-body">
				<p>
					{% blocktrans with thread_id=book.copy.thread_id%}This book was copy from <a href="http://www.tangthuvien.vn/forum/showthread.php?t={{thread_id}}">this</a>{% endblocktrans%}
				</p>
				<a class="btn btn-default" id="sync-copy-book" href="{% url copy_book_sync' book.id %}">{% trans "Sync new chapter" %}</a>
			</div>
		</div>
		{% endif %}
		<div class="panel panel-default favorite">
			<div class="panel-body">
				<button class="btn
					{% if not user.is_authenticated %}
						btn-disable login_required
					{% else %}
						{% if chapter.book.favorited_by_current_user %}btn-disable{% else %}btn-default{% endif %}
					{% endif %}
					" id="favorite_book"
					favorite="{% if chapter.book.favorited_by_current_user %}yes{% else %}no{% endif %}"
					{% if not user.is_authenticated %}title="{% trans 'Required you be logged-in to mark as favorite' %}"{% endif %}>
					{% if chapter.book.favorited_by_current_user %}
						{% trans "Favorite" %}
					{% else %}
						{% trans "Unfavorite" %}
					{% endif %}
				</button>
				<script>
(function($){
	var loading = false;
	$("#favorite_book").click(function(){
		if(loading){
			return;
		}
		loading = true;
		var request = {};
		request['url'] = '{% url "submit_favorite_book" %}';
		request['data'] = {'id' : '{{chapter.book.id}}'};
		request['type'] = 'POST';
		if($(this).attr('favorite') == 'no'){
			var ajaxComplete = function(){
				$("#favorite_book").attr('favorite', 'yes');
				$("#favorite_book").html('{% trans "Unfavorite" %}');
			}
		} else {
			var ajaxComplete = function(){
				$("#favorite_book").attr('favorite', 'no');
				$("#favorite_book").html('{% trans "Favorite" %}');
			}
		};
		request['success'] = function(data){
			loading = false;
			$("#favorite_book").removeClass('loading');
			ajaxComplete();
		};
		$("#favorite_book").addClass('loading');
		$.ajax(request);
	});
})(jQuery);
				</script>
			</div>
		</div>
		<div class="panel panel-default rating" id="book_rating">
			<div class="panel-heading">{% trans 'Rate book' %}</div>
			<div class="panel-body">
				<div class="result">
					{% blocktrans with book.rating.average_result as averate and book.rating.rating_count as rating_count %}
						Was rated <strong><span class="average-result">{{averate}}</span></strong>
						over <strong><span class="rating-count">{{rating_count}}</span></strong> ratings
					{% endblocktrans %}
				</div>
				<div class="rate-star">
					{% for i in book.rating.rating_range %}
					<button class="btn btn-default rate-star-{{i}}" data-rate-number="{{i}}"
					{% if book.rated_by_current_user %}
						disabled='disabled'
					{% elif not user.is_authenticated %}
					disabled='disabled' class='login_required'
					{% endif %}>{{i}}</button>
					{% endfor %}
				</div>
				<script type="text/javascript">
(function($){
	$("#book_rating .rate-star button").click(function(){
		var clickedButton = this;
		rateNumber = $(this).data('rate-number');

		$("#book_rating .rate-star button").attr('disabled', true);
		resultSpan = $("#book_rating .average-result");
		countSpan = $("#book_rating .rating-count");

		ratingCount = parseInt(countSpan.html());

		var newResult = (ratingCount * parseFloat(resultSpan.html()) + rateNumber) / (ratingCount + 1);
		newResult = newResult.toFixed(2);

		resultSpan.html(newResult);
		countSpan.html(ratingCount + 1);

		request = {};
		request['url'] = '{% url "submit_book_rating" %}';
		request['type'] = 'POST';
		request['data'] = {};
		request['data']['number'] = rateNumber;
		request['data']['book_id'] = '{{book.id}}';
		request['success'] = function(data){
			resultSpan.html(data['average_result'].toFixed(2));
			countSpan.html(data['rating_count']);
			$(clicked_button).removeClass('loading');
		}
		$(clickedButton).addClass('loading');
		$.ajax(request);
	});
})(jQuery);
				</script>
			</div>
		</div>
		{% include 'book/_book_attachments.phtml' %}
		{% include 'book/_book_and_author_description.phtml' %}
	</div>
</div>
{% endblock %}
