{% extends 'master.phtml' %}
{% load i18n %}
{% load static_tags %}
{% block title %}List of books{% endblock %}

{% block link %}
{% load_css static /book/rating_star.css %}
{% endblock %}

{% block content %}
{% include 'book/_read_pagination.phtml'%}
<div id="chapters">
	<div id="chapter" class="item chapter" item_id="{{chapter.id}}">
		<h2><span class="number">{{chapter.number}}</span> - {{chapter.title}}</h2>
		<div class="content">{{chapter.content|safe}}</div>
	</div>
</div>
{% include 'book/_read_pagination.phtml'%}
{% endblock %}
{% block sidebar %}
<div id="chapter-thank" class="widget">
	<h3>{% trans "Chapter thank" %}</h3>
	<div class="thank-count">{% trans "thanks" %} <span class="count">{{chapter.thank_count}}</span></div>
	<button class="thank-button{% if chapter.thanked_by_current_user %} disabled{% elif not user.is_authenticated %} disabled login_required{% endif %}">{% trans "thank poster for this chapter" %}</button>
	<script type="text/javascript">
(function($){
	var thankButton = $("#chapter-thank .thank-button");
	var thankCountDiv = $("#chapter-thank .count");
	var thankCount = parseInt(thankCountDiv.text());
	function thank(event){
		thankButton
			.unbind('click', thank)
			.addClass('disabled');
		var request = {};
		request['url'] = '{% url "summit_thank_request" %}';
		request['data'] = {};
		request['data']['chapter_id'] = '{{chapter.id}}';
		request['type'] = 'POST';
		request['success'] = function(data){
			console.log(data);
			thankButton.removeClass('loading');
		};
		thankButton.addClass('loading');
		$.ajax(request);

		thankCountDiv.html(thankCount + 1);
	}
	if(!thankButton.hasClass('disabled')){
		thankButton.click(thank)
	}
})(jQuery);
	</script>
	{% csrf_token %}
</div>
<div id="book" item_id="{{chapter.book.id}}" class="widget">
	<h3 class="header">{% trans "Book" %}</h3>
	<div class="content">
		<h4 class="title">{{book.title}}</h4>
		<div class="favorite">
			<button class="favorite" favorite="{% if chapter.book.favorited_by_current_user %}yes{% else %}no{% endif %}">Favorite</button>
			<script>
(function($){
	var loading = false;
	$("#book .favorite button").click(function(){
		if(loading){
			return;
		}
		loading = true;
		var request = {};
		request['url'] = '{% url "submit_favorite_book" %}';
		request['data'] = {'id' : '{{chapter.book.id}}'};
		request['type'] = 'POST';
		if($(this).attr('favorite') == 'no'){
			var ajaxComplete = function(){
				$("#book .favorite button").attr('favorite', 'yes');
			}
		} else {
			var ajaxComplete = function(){
				$("#book .favorite button").attr('favorite', 'no');
			}
		};
		request['success'] = function(data){
			loading = false;
			$("#book .favorite button").removeClass('loading');
			ajaxComplete();
		};
		$("#book .favorite button").addClass('loading');
		$.ajax(request);
	});
})(jQuery);
			</script>
		</div>
		<div class="rating">
			<div class="result">
				<span class="average-result">{{book.rating.average_result}}</span>/<span class="rating-count">{{book.rating.rating_count}}</span>
			</div>
			<div class="rate-star">
				{% for i in book.rating.rating_range %}
				<button class="rate-star-{{i}}" data-rate-number="{{i}}"
				{% if book.rated_by_current_user %}
					disabled='disabled'
				{% elif not user.is_authenticated %}
				disabled='disabled' class='login_required'
				{% endif %}>{{i}}</button>
				{% endfor %}
			</div>
			<script type="text/javascript">
(function($){
	$("#book .rating .rate-star button").click(function(){
		var clickedButton = this;
		rateNumber = $(this).data('rate-number');

		$("#book .rating .rate-star button").attr('disabled', true);
		resultSpan = $("#book .rating .average-result");
		countSpan = $("#book .rating .rating-count");

		ratingCount = parseInt(countSpan.html());

		var newResult = (ratingCount * parseFloat(resultSpan.html()) + rateNumber) / (ratingCount + 1);
		newResult = newResult.toFixed(2);

		resultSpan.html(newResult);
		countSpan.html(ratingCount + 1);

		request = {};
		request['url'] = '{% url "submit_book_rating" %}';
		request['type'] = 'POST';
		request['data'] = {};
		request['data']['number'] = rateNumber;
		request['data']['book_id'] = '{{book.id}}';
		request['success'] = function(data){
			resultSpan.html(data['average_result'].toFixed(2));
			countSpan.html(data['rating_count']);
			$(clicked_button).removeClass('loading');
		}
		$(clickedButton).addClass('loading');
		$.ajax(request);
	});
})(jQuery);
			</script>
		</div>
		<div class="description">{{book.description}}</div>
	</div>
</div>
<div id="author" author_id="{{book.author.id}}" class="widget">
	<h3 class="header">{% trans "Author" %}</h3>
	<div class="content">
		<h4 class="title">{{book.author.name}}</h4>
		<div class="information">{{book.author.information}}</div>
	</div>
</div>
{% endblock %}