{% extends 'base.html' %}
{% load i18n %}
{% load static_tags %}

{% block title %}{{book.title}} - {% blocktrans with number=chapter.number%}Chapter {{number}}{% endblocktrans %}{% endblock %}

{% block meta-description %}{{book.description|striptags|escapejs}}{% endblock %}

{% load_css static /book/style.css %}
{% load_js static /book/read.js %}

{% block content %}
{% include 'book/onetime_notification/user_log_notification.phtml' %}
<div class="row">
	<div class="col-lg-9">
	    <div class="row">
    		<h3 class="col-lg-9">{{book.title}} / {{book.author.name}}</h3>
            <div class="col-lg-3" id="read_config">
                {% include 'book/_config_reading_section.phtml' %}
            </div>
        </div>
		<div class="well">
			{% include 'book/_read_pagination.phtml'%}
			<div id="chapters">
				<div id="chapter" class="item chapter" item_id="{{chapter.id}}">
					<h2><span class="number">{{chapter.number}}</span> - {{chapter.title}}</h2>
					<div class="content"><script type="text/javascript">
						jQuery(function(){
							apply_reading_section_config(jQuery, '{{config_reading_section_form.styles}}');
						});
					</script>{{chapter.content|safe}}</div>
				</div>
			</div>
			{% include 'book/_read_pagination.phtml'%}
        </div>
        <div id="after-chapter-content" class="btn-group btn-group-justified">
            <a id="post-new-chapter" href="{% url 'post_new_chapter' book.id %}" class="btn btn-default">{% trans 'Add Chapter' %}</a>
        	{% if chapter.user.id = request.user.id %}
        	<a id="edit-chapter" href="{% url 'edit_chapter' chapter.id %}" class="btn btn-default">{% trans 'Edit Chapter' %}</a>
        	{% endif %}
        </div>
		<script>
		    var disqus_url = get_real_link("{% url 'book_read' book.slug %}");
		</script>
		{% include 'disqus.phtml'%}
	</div>
	<div class="col-lg-3 sidebar-margin-top">
		<div id="chapter-thank" class="panel panel-default">
			<div class="panel-heading">{% blocktrans with name=chapter.user.username %}Thank {{name}}{% endblocktrans %}</div>
			<div class="panel-body">
				<div class="thank-count">
					<button
						class="
						btn thank-button
						{% if chapter.thanked_by_current_user %}btn-disable
						{% elif not user.is_authenticated %}btn-disable login_required
						{% else %}btn-default
						{% endif %}"
						title="{% if chapter.thanked_by_current_user %}{% trans 'You thanked already' %}{% elif not user.is_authenticated %}{% trans 'Required you be logged-in to thank' %}{% else %}{% trans 'Thank the poster' %}{% endif %}"
						>
						<span class="count">{{chapter.thank_count}}</span> {% trans "thank(s)" %}
					</button>
				</div>
				<script type="text/javascript">
				jQuery(function(){
					attach_thank_button(jQuery, '{{chapter.id}}', '{% url "summit_thank_request" %}');
				});
				</script>
				{% csrf_token %}
			</div>
		</div>
		{% include 'book/_book_sync_copy.phtml' %}
		{% include 'book/_book_favorite.phtml' %}
		{% include 'book/_book_rating.phtml' %}
		{% include 'book/_book_generate_prc.phtml' %}
		{% include 'book/_book_attachments.phtml' %}
	</div>
</div>
{% endblock %}
