<html>
    <head>
        <script>
        // vbb cookie function
        function set_cookie(name,value,date) {
            if (date) {
                var expires = "; expires="+date.toGMTString();
            }
            else var expires = "";
            document.cookie = name+"="+value+expires+"; path=/";
        }

        function fetch_cookie(name) {
            var nameEQ = name + "=";
            var ca = document.cookie.split(';');
            for(var i=0;i < ca.length;i++) {
                var c = ca[i];
                while (c.charAt(0)==' ') c = c.substring(1,c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
            }
            return null;
        }

        function eraseCookie(name) {
            var now = new Date();
            now.setDate(now.getDate() - 1);
            set_cookie(name,"",now);
        }
        </script>
        <style>

.tcat
{
    background: #3A609A url(tangthuvientem/ttv/tcat.png) repeat-x bottom left;
    color: #FFFFFF;
    font: bold 10pt verdana, geneva, lucida, 'lucida grande', arial, helvetica, sans-serif;
    border: 1px solid #ccc;
    border-bottom-color: #ccc;
    text-shadow: 1px 1px 1px #555;
    padding: 7px
}
        </style>
    </head>
    <body>
        <h1>Test cloned book notification</h1>
        <script src="{% url 'cloned_book_notification' thread_id %}"></script>
    </body>
</html>