{% load i18n %}
<script>
ONETIME_NOTIFICATION_SUBMIT_URL = '{% url "submit_onetime_notification" %}';
AJAX_LIST_BOOK_URL = "{% url 'ajax_list_books' %}";
UPLOAD_BOOK_ATTACHMENT_AJAX_URL = "{% url 'upload_book_attachment_ajax' %}";
ADD_BOOK_AUTHOR_AJAX_URL = '{% url "add_book_author_ajax" %}';
ADD_BOOK_TYPE_JS_AJAX_URL = '{% url "add_book_type_ajax" %}';
AJAX_BOOK_READING_CONFIG_URL = '{% url "ajax_book_reading_config" %}';
SUBMIT_BOOK_RATING_URL = '{% url "submit_book_rating" %}';
SUBMIT_BOOK_FAVORITE_URL = '{% url "submit_favorite_book" %}';

LOADING_IMAGE_HTML = '<img class="loading" src="{{STATIC_URL}}{{CURRENT_STYLE}}/img/ajax-loader.gif" />';
STR_CREATE_NEW = '{% trans "-create-new-" %}'
LANG_PRC_IS_GENERATING = "{% trans 'PRC is generating' %}";
LANG_PRC_IS_GENERATED = "{% trans 'PRC was generated' %}";
LANG_UNFAVORITE = '{% trans "Unfavorite" %}';
LANG_FAVORITE = '{% trans "Favorite" %}';
</script>