{% load i18n %}
{% load static_tags %}
{% load url from future %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xml:lang="{{ LANGUAGE_CODE }}" lang="{{ LANGUAGE_CODE }}" version="-//W3C//DTD XHTML 1.1//EN" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>{{SITE_NAME}} - {% block title %}{% endblock %}</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="cache-control" content="public" />
		<meta name="robots" content="follow, all" />
		<meta name="language" content="{{ LANGUAGE_CODE }}" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="description" content="{% block meta-description %}{% trans 'Book reading website' %}{% endblock %}" />
		<meta name="keywords" content="tangthuvien, ttv, kiếm hiệp, {% block meta-keywords %}{% endblock %}" />
		<meta name="author" content="Antipro.VN" />
		{% block meta %}{% endblock %}
		<link rel="pingback" href="/xmlrpc/" />
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="home" href="{% url 'homepage' %}" />
		{% block link %}{% endblock %}
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap/{{CURRENT_STYLE}}.css" />
		{% load_css static /style.css %}
		{% print_css %}
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
		<script>
			if (!window.jQuery){
				document.write('<script src="{{ STATIC_URL }}js/jquery.1.10.2.min.js"></sc' + 'ript>');
			}
			jQuery.noConflict();
		</script>
		{% include '_js_defined_params.phtml' %}
		<script src="{{ STATIC_URL }}js/head_define.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.cookie.js"></script>
		{% block script %}{% endblock %}
		{% load_js static /bootstrap.min.js %}
		{% load_js static /foot_define.js %}
	</head>
	<body id="{% block page_id %}{% endblock %}">
		{% include '_top_nav.phtml' %}
		<div class="container">
			{% include '_top_banner.phtml' %}
			{% block slider %}{% endblock %}
			<div id="content" class="hfeed">
				{% block content %}

				{% endblock %}
			</div>
			<footer>
				<div class="row">
					<div class="col-lg-12">
						{% include '_footer_nav.phtml' %}
						<p>
							{% blocktrans %}Powered by <a href="/">tangthuvien.vn</a>{% endblocktrans %}
						</p>
					</div>
				</div>
			</footer>
		</div>
	{% print_js %}
	</body>
</html>
